version: '3'
services:
  database:
    image: postgres
    container_name: database
    read_only: false
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql:ro
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taiko

  backend:
    build: ./backend
    container_name: backend
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/taiko
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 4200:80
    # volumes:
      # - ./reverse-proxy/http-taiko.conf.template:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  data:

